services:
  openai-proxy:
    build: .
    container_name: OpenAI-Proxy
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./.config.yml:${PROXY_CONFIG_PATH:-/app/.config.yml}:ro
    restart: always

